[package]
name = "varlong"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
ndarray = "0.16.1"
ndarray-csv = "0.5.4"
rayon = "1.11.0"
smartcore = "0.4.9"
